---
- name: "Copying docker.list to /etc/apt/sources.list.d/"
  copy:
    src: "{{ role_path }}/files/docker.list"
    dest: "/etc/apt/sources.list.d/"
  become: true
  become_method: sudo

- name: "Create /etc/apt/keyrings/ directory"
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  become_method: sudo

- name: Ensure Docker GPG key is readable by all users
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  become_method: sudo

- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Installing Docker"
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: true
  become_method: sudo
