---
- name: "Building toolkit"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-system"
    - role: "roles/configure-tmux"
    - role: "roles/configure-vim"
    - role: "roles/configure-terminal"
    - role: "roles/configure-browser"
    - role: "roles/install-tools"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - GitHub.copilot
            - snyk-security.snyk-vulnerability-scanner
            - ms-azuretools.vscode-docker
            - silofy.hackthebox


