---
# tasks file for configure-vim
- name: "Configure Vim"
  apt:
    name: vim
    state: present
  become: true
  become_method: sudo
- name: "Copying Vim Config"
  copy:
    src: "{{ role_path }}/files/.vimrc"
    dest: "{{ ansible_env.HOME }}"
